LeekHub/leek-fund

- src/extension.ts
- src/registerEvent.ts
- src/service.ts
> feat: 基金添加时，提供搜索提示功能

- src/extension.ts
> fixed issue #31

- src/explorer/service.ts
- src/utils.ts
> 根据自选股所有的交易市场优化交易时间判断

- src/utils.ts
> 修复异步API获取假日导致全局假日变量初始化未能获取假日的bug

- src/extension.ts
- src/utils.ts
> 修复休市后的休眠bug

- src/explorer/service.ts
> 修复恒生指数添加无效的bug

- package.json
- src/explorer/stockService.ts
- src/extension.ts
- src/globalState.ts
- src/registerCommand.ts
- src/shared/leekConfig.ts
- src/shared/remindNotification.ts
- src/shared/utils.ts
- src/webview/setStocksRemind.ts
- template/stock-remind.html
- 提醒的涨跌状态判断从「昨收价-现价」改为「现价-上一秒价」
- 修复浮点数精度问题
> fix: 个股提醒的bug

- README.md
- document.md
- package.json
- src/explorer/stockService.ts
- src/extension.ts
- src/globalState.ts
- src/registerCommand.ts
- src/shared/constant.ts
- src/shared/leekTreeItem.ts
- src/shared/utils.ts
- src/statusbar/statusBar.ts
document.md 添加了 关于 「状态栏、侧栏模板」的使用
> 优化:状态栏个股点击快速更换，自定义状态栏、侧栏模板格式

- src/registerCommand.ts
- src/statusbar/statusBar.ts
股票状态栏新选择的股票数量少于之前的数量时，不会删除未选择的股票的bug
> fix: 股票状态栏新选择的股票数量少于之前的数量时，不会删除未选择的股票的bug

- package.json
- src/explorer/binanceProvider.ts
- src/explorer/binanceService.ts
- src/explorer/stockService.ts
- src/extension.ts
- src/registerCommand.ts
- src/shared/constant.ts
- src/shared/leekConfig.ts
- src/shared/leekTreeItem.ts
- src/shared/typed.ts
- src/shared/utils.ts
- tsconfig.json
- [style] spell error fix, `calcFixedPirceNumber` -> `calcFixedPriceNumber`
- [feat] 对接binance接口, 获取交易对列表及交易详情
- [feat] 实现对交易对的增加\删除\置顶
- [chore] compile ts to `ES2020`
#35 #107
> 新增对数字货币行情的简单支持

- src/shared/utils.ts
> chore: config holidays 2021

- src/webview/setStocksRemind.ts
> fix: set stock remind not work

- src/webview/fundTrend.ts
Close #94 
令基金的`单位净值走势`和`累计收益走势`两个 highChart 图表背景沉浸式，实时走势图则直接反转颜色。
> feat: immersive background color #94

- package.json
- src/extension.ts
- src/globalState.ts
- src/registerCommand.ts
- src/webview/fundTrend.ts
修复了你说的[这个问题](https://github.com/LeekHub/leek-fund/pull/123#issuecomment-741886022)
> fix: 背景勾选状态持久化

- src/shared/remindNotification.ts
> fix: 当设置股价下跌提醒时，在早上未开盘期间，股价为0.00，这个时候会提示下跌到了0.00

- package.json
- src/extension.ts
- src/output/flash-news/FlashNewsDaemon.ts
- src/output/flash-news/NewsFlushServiceAbstractClass.ts
- src/output/flash-news/impl/Jin10FlushService.ts
- src/registerCommand.ts
> Feature：金十快讯

- package.json
- src/output/flash-news/FlashNewsDaemon.ts
- src/output/flash-news/NewsFlushServiceAbstractClass.ts
- src/output/flash-news/impl/Jin10FlushService.ts
- src/output/flash-news/impl/XuanGuBaoFLushServices.ts
还优化了更新statusbar的方法，用了节流函数减少频繁更新statusbar
> feat: 选股宝异动快讯，金十全量输出

- src/explorer/fundService.ts
- src/explorer/stockService.ts
- src/extension.ts
- src/statusbar/statusBar.ts
> fix: statusbar 股价更新滞后问题

- src/webview/donate.ts
- src/webview/fundPosition.ts
- src/webview/setAmount.ts
- template/fund-amount.html
- template/stocks-view.html
perf: 优化持仓页面首次数据加载的逻辑
fixed #172
> fix: 百度libs的静态文件部分用户存在加载失败

- src/explorer/binanceService.ts
> fix: 低版本vscode不支持Promise.allSettled的问题

- package.json
https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location
> add "extensionKind"

- src/webview/setAmount.ts
- template/fund-amount.html
1、修复无法保存持仓金额的问题
2、更新持仓金额和成本价后，更新基金收益率
> 修复无法保存持仓金额的问题

- package.json
- src/registerCommand.ts
- src/shared/leekConfig.ts
新加的基金分组功能挺好的，如果能重命名分组名称就更好了。顺手加上了。
> feat: 支持重命名基金分组

- src/explorer/stockService.ts
> refactor(stock): 优化股票刷新速度

- demo/stocktrend.html
- src/webview/stockTrend.ts
- src/webview/stockTrendPic.ts
- template/flow.html
> fix: 使用 https 协议，防止在 gitpod coding 等 ide 环境下 http 协议被浏览器安全策略限制

- package.json
- resources/dark/down.svg
- resources/dark/up.svg
- resources/light/down.svg
- resources/light/up.svg
- src/registerCommand.ts
- src/shared/leekConfig.ts
1、第一个功能看一下是否需要。当股票状态栏没有股票的时候，自动隐藏（正在显示的）股票状态栏；当给股票状态栏增加股票的时候，自动显示（正在隐藏的）股票状态栏。
2、第二个功能的实现有点绕。因为在上移或者下移股票的时候，需要找到前一个或者后一个同市场的股票进行位置交换。
> feat(statusbar): 股票状态栏根据需要展示的股票数量进行自动隐藏和显示 fixed #279 & feat(stock): 增加股票上移和下移功能

- template-packages/leek-center/src/view/data-center/bkhq.tsx
- template-packages/leek-center/src/view/data-center/index.tsx
通过iframe简单实现效果，目前只有固定【昨日涨停板】【昨日连扳】两个板块行情
> feat(stock): 韭菜中心=>数据中心 增加板块行情

- template-packages/leek-center/src/view/data-center/bkhq/index.less
- template-packages/leek-center/src/view/data-center/bkhq/index.tsx
fix(韭菜中心>数据中心): 板块行情增加默认值，避免点击工具菜单出现无数据现象
style(韭菜中心>数据中心): 板块行情根据vscode主题色显示深色和浅色
style(韭菜中心>数据中心): 板块详情显示优化，设置minHeight避免终端压缩页面显示
> 韭菜中心>数据中心  板块详情

- src/webview/stockTrend.ts
> fix(stock): 修复深证指数面板显示bug

- src/explorer/forexService.ts
> fix(forex): 修复cheerio导入错误

- src/shared/holidayHelper.ts
获取节日信息的接口，目前使用的 https 协议，控制台上可以看到一些报错
> 调整为节日信息获取接口为 https协议

- package.json
- src/extension.ts
相关文档:
[onStartupFinished](https://code.visualstudio.com/api/references/activation-events#onStartupFinished)
> perf: ⚡️ 激活事件改为`onStartupFinished`, 提升冷启动性能

- package.json
- src/extension.ts
- src/globalState.ts
- src/registerCommand.ts
- src/webview/stockTrend.ts
>  feat: 增加在个性定制中可切换股票详情K线图样式

- template-packages/leek-center/src/view/data-center/nxfxb/HSGT.tsx
- template-packages/leek-center/src/view/data-center/nxfxb/services.ts
> refactor(韭菜中心>数据中心>牛熊风向标): 调整东财北向资金接口

- package.json
- src/extension.ts
- src/registerCommand.ts
- src/statusbar/statusBar.ts
- template-packages/leek-center/package.json
Status Bar 修改
1. 添加```LeekFund: Toggle Status Bar Visibility```命令
2. 修改`\leek-fund\template-packages\leek-center\package.json`的build以适配windows
modified:   package.json
modified:   src/extension.ts
modified:   src/registerCommand.ts
modified:   src/statusbar/statusBar.ts
modified:   template-packages/leek-center/package.json
> feat: 添加LeekFund: Toggle Status Bar Visibility命令

- src/explorer/fundService.ts
- src/shared/leekTreeItem.ts
- src/webview/setAmount.ts
- template-packages/leek-center/src/components/fund-info-panel/info-header.tsx
https://github.com/LeekHub/leek-fund/issues/389
> fix(fund): 更换基金数据接口

- src/explorer/fundService.ts
> fix: 状态栏计算当日收益错误

- .vscode/bookmarks.json
- package.json
- src/explorer/stockService.ts
- src/extension.ts
- src/globalState.ts
- src/registerCommand.ts
- src/statusbar/Profit.ts
- src/webview/setStockPrice.ts
- template-packages/leek-center/package.json
- template/stock-price.html
- yarn.lock
> feat: 增加股票收益计算

- .vscode/bookmarks.json
- package.json
- src/_test/runTest.ts
- src/explorer/stockService.ts
- src/statusbar/Profit.ts
- src/webview/setStockPrice.ts
- template-packages/leek-center/package.json
- template/stock-price.html
- yarn.lock
过滤掉了这些
sh000001,sh000300,sh000016,sh000688,usr_ixic,usr_dji,usr_inx,nf_IF0,nf_IH0,nf_IC0,nf_IM0,hf_OIL,hf_CHA50CFD
> fix: 计算股票收益只计算自选的股票

- package.json
- src/explorer/stockProvider.ts
- src/explorer/stockService.ts
- src/globalState.ts
- src/registerCommand.ts
- src/shared/leekTreeItem.ts
- src/shared/typed.ts
- src/shared/utils.ts
Reverts LeekHub/leek-fund#504
因 依赖 `puppeteer` 过重不建议 合并。建议改造代码
> Revert "增加涨跌停盯盘"

- src/shared/typed.ts
- src/webview/setAmount.ts
- template/fund-amount.html
fix: https://github.com/LeekHub/leek-fund/issues/339
> feat: 持仓金额改成持仓份额

- src/registerCommand.ts
feat: https://github.com/LeekHub/leek-fund/issues/517
> feat: 支持导入导出设置
